scene.onHitWall(SpriteKind.Player, function (sprite, location) {
	
})
function GroupTekis () {
    for (let index = 0; index <= 5; index++) {
        Teki = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111311bf.......
            ......fffcdb1bdffff.....
            ....fc111cbfbfc111cf....
            ....f1b1b1ffff1b1b1f....
            ....fbfbffffffbfbfbf....
            .........ffffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.Enemy)
        Teki.ax = 30 + index * 30
        Teki.y = 30
        Teki.setBounceOnWall(true)
        Teki.setVelocity(100, 10)
    }
}
let Teki: Sprite = null
GroupTekis()
